### ISSUE TITLE
Replace JBoss Keycloak Image with a More Current One

### ISSUE THREAD

**Issue by alexanderkiel** [samply/blaze#830]
For example `bitnami/keycloak:20` is current. Bute the custom realm import is not available there. So that needs more work. A temporary compose file looks like this:

```
version: '3.7'
services:
  postgresql:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "bn_keycloak"
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_DB: "bitnami_keycloak"
  keycloak:
    image: "bitnami/keycloak:20"
    environment:
      KEYCLOAK_DATABASE_PASSWORD: "keycloak"
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
    - "8090:8080"
    volumes:
    - "../../.github/openid-auth-test/realm.json:/tmp/realm.json"
    depends_on:
    - postgresql
  blaze:
    image: "samply/blaze:0.18"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/auth/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
```
